### ISSUE TITLE
Running into infinite loop or endless recursion?

### ISSUE THREAD

**Issue by mattdesl** [substack/static-module#18]
The following test in brfs seems to be causing an endless loop. 

https://github.com/substack/brfs/blob/master/test/files/with_comments.js

This was introduced with #15 by @eush77. However, the test was failing in previous versions of static-module with the following:

```
not ok 1 /projects/oss/brfs/test/files/with_comments.js:4 module.exports = function () {       ^ ParseError: Unexpected token
```

**Comment by eush77** [comment]
I believe the issue with this test is that the main function is never called and `tap` is stuck waiting for `t.equal` call to happen (according to the `plan(1)` directive).

If I add this call to the end of `files/with_comments.js`:

```js
module.exports();
```

then I get this error instead:

```
evalmachine.<anonymous>:6
        tag = document.createElement('style'),
              ^

ReferenceError: document is not defined
    at Object.module.exports (evalmachine.<anonymous>:6:15)
    at Object.1 (evalmachine.<anonymous>:14:8)
    at s (evalmachine.<anonymous>:1:220)
    at e (evalmachine.<anonymous>:1:391)
    at evalmachine.<anonymous>:1:409
    at ContextifyScript.Script.runInNewContext (vm.js:18:15)
    at Object.exports.runInNewContext (vm.js:49:17)
```

Finally, the code that `vm` is trying to execute seems legit to me:

```js
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var style = "<b>beep boop</b>\n";

module.exports = function () {
    var
        tag = document.createElement('style'),
        content = document.createTextNode(style);

    tag.appendChild(content);
    document.body.appendChild(tag);
};


module.exports();

},{}]},{},[1])
```

So I think this is not a `static-module` issue. Can you confirm that @mattdesl?

**Comment by mattdesl** [comment]
> I believe the issue with this test is that the main function is never called and tap is stuck waiting for t.equal call to happen (according to the plan(1) directive).

Ah yes, d'oh. :laughing: 

Thanks for the second pair of eyes. Everything is working well!
